# Generated by Django 4.0.6 on 2022-12-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_post_agregarcomentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerrosyGatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('raza', models.CharField(max_length=250)),
                ('descripcion', models.TextField(null=True)),
                ('adopcion', models.CharField(max_length=250)),
                ('gastos', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
