# Generated by Django 4.0.6 on 2022-12-24 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_perrosygatos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerrosyGatos',
        ),
    ]
